version: '3'

services:
  driver:
    build: .
    command: sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000"
    volumes:
      - .:/driver
    ports:
      - "8001:8000"
      - postgres
  postgres:
    image: postgres
    expose:
      - "5432"
    volumes:
      - db:/var/lib/postgresql/data

    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '1234'
      POSTGRES_DB: 'otol'

volumes:
  db: